name: Code For Chico
description: A Code for America Brigade
url: https://codeforchico.org
repository: https://github.com/CodeForChico/Website1.0/

#https://stackoverflow.com/questions/16316311/github-pages-and-relative-paths
#

# Handling Reading
safe                : false
include             : ["node_modules"]

baseurl: /Website1.0